[package]
name = "particle-filter"
version = "0.1.0"
authors = ["Kaelin Laundry <wasabifan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"